name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint
      run: |
        flake8 . --exit-zero --count --max-complexity=10 --max-line-length=88 --statistics --exclude=./migrations,./venv
#    - name: Autoformat
#      run: |
#        black . --check --exclude \migrations
    - name: Cyclomatic complexity
      run: |
        radon cc . -a -s -i venv,migrations
    - name: Maintainability index
      run: |
        radon mi . -i venv,migrations
    - name: Static type checking
      run: |
        mypy . --exclude migrations --ignore-missing-imports
    - name: Test
      run: |
        pytest --cov=app -v
